site_name: Steam Unlock ONENNABE
site_description: Official guide and documentation for Steam Unlock ONENNABE
site_url: https://barryhamsy.github.io/onennabe-docs/

theme:
  favicon: steamunlock_wannabe.ico
  logo: steamunlock_wannabe.ico
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

extra_css:
  - stylesheets/steam-theme.css

nav:
  - Home: index.md
  - Getting Started:
    - Downloading ONENNABE: downloading-onennabe.md
    - Installation: installation.md
    - CD Key Activation: cd-key-activation.md
  - Using ONENNABE:
    - Settings Explained: settings.md
    - Cloud Save Settings: cloud-save-settings.md
    - Unlocking Games: unlocking-games.md
    - Library Tab: library-tab.md
    - Removing Games from Library: library-remove-games.md
    - Bypass & Online Patch: bypass-and-online-patch.md
    - Tools Section Explained: tools.md
    - Denuvo Games: denuvo-games.md
    - Cloud Redirect: cloudredirect.md
    - Hypervisor Games: hypervisor.md
  - Help, my game is not unlocking!!:
    - Troubleshooting: troubleshooting.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - attr_list
